### ISSUE TITLE
A user can keep a list of countries they are tracking 

### ISSUE THREAD

**Issue by robo360** [BlaiseMunyampirwa/COVID-19-tracker-android-app#13]
- [ ] add a session management 

- [ ] add a menu item of tracked countries

- [ ] create a fragment for tracked countries

- [ ] add a recyclerView of tracked countries 

- [ ] add a search and add to tracked countries
